// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeP1xCfnadFWis7Lh2g6qRA8TgbftvLAo',
    appId: '1:373268750734:web:925de551b34c8cc4f184df',
    messagingSenderId: '373268750734',
    projectId: 'my-mini-progect',
    authDomain: 'my-mini-progect.firebaseapp.com',
    storageBucket: 'my-mini-progect.appspot.com',
    measurementId: 'G-5NHDR8D9HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NHy2zg4qS3Lyk4INNhgY14nH5sJDHrk',
    appId: '1:373268750734:android:d7fd3693d53e984ff184df',
    messagingSenderId: '373268750734',
    projectId: 'my-mini-progect',
    storageBucket: 'my-mini-progect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKLt3m7-B6zIT5_5xw4NWc_nEVO6xSAIM',
    appId: '1:373268750734:ios:60d2df89956bac90f184df',
    messagingSenderId: '373268750734',
    projectId: 'my-mini-progect',
    storageBucket: 'my-mini-progect.appspot.com',
    iosBundleId: 'com.example.login',
  );
}
